version: "2.1"
services:
    db:
        build: ../pgsql/
        env_file:
            - options.env
        volumes:
            - pg_data:/var/lib/postgresql/data

    icinga2:
        build: ../icinga2/
        depends_on:
            - db
        env_file:
            - options.env
        volumes:
            - icinga2_config:/etc/icinga2/
            - icinga2_socket:/run/icinga2/cmd/
            - icinga2_api_objects:/var/lib/icinga2/api
        hostname: docker-icinga2

    monitutor-web:
        build: ../monitutor
        env_file:
            - options.env
        volumes:
            - ssl_certs:/etc/apache2/ssl
            - monitutor_appconfig:/var/www/web2py/applications/MoniTutor/private
            - web2py_db:/var/www/web2py/applications/MoniTutor/databases
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - db
            - icinga2
        ports:
            - 443:443
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 15s
            timeout: 5s
            retries: 5

    monitutor-scheduler:
        build: ../monitutor
        env_file:
           - options.env
        volumes_from:
            - monitutor-web
        volumes:
            - icinga2_config:/etc/icinga2/
        depends_on:
            monitutor-web:
                condition: service_healthy
        command: ["python", "./web2py.py", "-K", "MoniTutor:init:main"]

    rabbit-mq:
        build: ../rabbit-mq
        ports:
            - 15674:15674
            - 15671:15671
            - 8080:15672
            - 5672:5672
        volumes:
            - ssl_certs:/ssl:ro
        hostname: docker-rabbit

    resultwriter:
        build: ../monitutor-tunnel
        volumes:
            - icinga2_socket:/run/icinga2/cmd/
        depends_on:
            - rabbit-mq
            - icinga2
        env_file:
            - options.env
        command: ["python", "start_resultwriter.py", "-a", "rabbit-mq", "-vvv"]

    tunnelserver:
        build: ../monitutor-tunnel
        volumes:
            - ssl_certs:/etc/ssl:ro
        depends_on:
            - rabbit-mq
            - icinga2
        ports:
            - 13337:13337
        env_file:
            - options.env
        command: ["python", "start_server.py", "-u", "${DATABASE_USER}", "-w", "${DATABASE_PASSWORD}", "-j", "${DATABASE_HOST}", "-n", "${POSTGRES_DB}", "-r", "rabbit-mq", "-vv"]

volumes:
    monitutor_appconfig:
    ssl_certs:
    pg_data:
    web2py_db:
    icinga2_config:
    icinga2_api_objects:
    icinga2_socket:
