version: "2.1"
services:
    db:
        image: postgres:9
        env_file:
            - options.env
        volumes:
            - pg_data:/var/lib/postgresql/data

    monitutor-web:
        build: ../monitutor
        env_file:
            - options.env
        volumes:
            - ssl_certs:/etc/apache2/ssl
            - monitutor_appconfig:/var/www/web2py/applications/MoniTutor/private
            - web2py_db:/var/www/web2py/applications/MoniTutor/databases
            - web2py_uploads:/var/www/web2py/applications/MoniTutor/uploads
            - /etc/localtime:/etc/localtime:ro
        depends_on:
            - db
        ports:
            - 443:443
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 15s
            timeout: 5s
            retries: 5

    rabbit-mq:
        build: ../rabbit-mq
        ports:
            - 15674:15674
            - 15671:15671
            - 8080:15672
            - 5672:5672
        volumes:
            - ssl_certs:/ssl:ro
        hostname: docker-rabbit

    couchdb:
        build: ../couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=admin
        ports:
            - 5984:5984
        volumes:
            - couchdb_config:/opt/couchdb/etc
            - couchdb_data:/opt/couchdb/data

    coudchdb-resultwriter:
        build: ../monitutor-tunnel
        depends_on:
            - rabbit-mq
            - couchdb
        env_file:
            - options.env
        command: ["python", "start_couchDB_resultwriter.py", "-a", "rabbit-mq", "-vvv", "-u", "admin", "-p", "admin"]

    tunnelserver:
        build: ../monitutor-tunnel
        volumes:
            - ssl_certs:/etc/ssl:ro
        depends_on:
            - rabbit-mq
        ports:
            - 13337:13337
        env_file:
            - options.env
        command: ["python", "start_server.py", "-u", "${DATABASE_USER}", "-w", "${DATABASE_PASSWORD}", "-j", "${DATABASE_HOST}", "-n", "${POSTGRES_DB}", "-r", "rabbit-mq", "-vv"]

    ## tunnelclient can be used for testing
    #tunnelclient:
        #build: ../monitutor-tunnel
        #depends_on:
        #    - tunnelserver
        #command: ["python", "start_client.py", "-u", "testuser", "-w", "testhmac", "-p", "13337", "-a", "tunnelserver", "-vvvv", "-n", "itsclient"]

volumes:
    monitutor_appconfig:
    ssl_certs:
    pg_data:
    web2py_db:
    web2py_uploads:
    couchdb_data:
    couchdb_config:
