version: '2.0'

services:
    db:
        build: ../pgsql/
        env_file:
            - options.env
        volumes:
            - pg_data:/var/lib/postgresql/data

    icinga2:
        build: ../icinga2/
        depends_on:
            - db
        env_file:
            - options.env
        volumes:
            - icinga2_config:/etc/icinga2/
            - icinga2_socket:/run/icinga2/cmd/
            - icinga2_api_objects:/var/lib/icinga2/api
        hostname: docker-icinga2

    monitutor-web:
        build: ../monitutor
        env_file:
            - options.env
        volumes:
            - ssl_certs:/etc/apache2/ssl
            - monitutor_appconfig:/var/www/web2py/applications/MoniTutor/private
            - web2py_db:/var/www/web2py/applications/MoniTutor/databases
        depends_on:
            - db
            - icinga2
        ports:
            - 443:443

    monitutor-scheduler:
        build: ../monitutor
        env_file:
           - options.env
        volumes_from:
            - monitutor-web
        volumes:
            - icinga2_config:/etc/icinga2/
        depends_on:
            - db
            - monitutor-web
            - icinga2
        command: python ./web2py.py -K MoniTutor:init:main

    monitutor-tunnel:
        build: ../monitutor-tunnel
        env_file:
            - options.env
        volumes:
            - ssl_certs:/etc/ssl:ro
            - icinga2_socket:/run/icinga2/cmd/
        depends_on:
            - db
            - icinga2
            - monitutor-web
        ports:
            - 5998:5998
        command: ["-p", "5998", "-vv"]

volumes:
    monitutor_appconfig:
    ssl_certs:
    pg_data: 
    web2py_db:
    icinga2_config:
    icinga2_api_objects:
    icinga2_socket:
