version: '2.0'

services:

    db:
        build: ../pgsql/
        env_file:
            - options.env
        volumes:
            - pg_data:/var/lib/postgresql/data
    icinga:
        build: ../icinga2/
        depends_on:
            - db
        env_file:
            - options.env
        volumes:
            - templates:/etc/icinga2/conf.d/monitutor
            - object:/var/lib/icinga2/api

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - db

    monitutor-web:
        build: ../web2py
        env_file:
            - options.env
        volumes:
            - certs:/etc/apache2/ssl
            - config:/var/www/web2py/applications/MoniTutor/private
            - web2py_db:/var/www/web2py/applications/MoniTutor/databases
        depends_on:
            - db
        ports:
            - 443:443

    web2py-scheduler:
        build: ../web2py
        env_file:
           - options.env
        volumes_from:
            - monitutor-web
        depends_on:
            - db
            - monitutor-web
        command: python ./web2py.py -K MoniTutor:init:main

volumes:
    config:
    certs:
    pg_data: 
    web2py_db:
    templates:
    object:
